apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Springboot-Demo-App"
  description: "Demo CRUD Springboot App with Swagger & H2DB"
  annotations:
    github.com/project-slug: abbhishekpandey47/demo
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
