apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo"
  description: "Demo Springboot application"
  annotations:
    github.com/project-slug: abbhishekpandey47/demo
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
